// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr8Fzd32H8Jqnp2MOrMTZb1IXIRF7-RdI',
    appId: '1:200080333384:web:0e5ae995acef7bf505967d',
    messagingSenderId: '200080333384',
    projectId: 'tripzo-a6939',
    authDomain: 'tripzo-a6939.firebaseapp.com',
    storageBucket: 'tripzo-a6939.firebasestorage.app',
    measurementId: 'G-R39E4KV6RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP-kppArFz59dVCVATHTBihi4cujHJPjI',
    appId: '1:200080333384:android:27a6d2917234190b05967d',
    messagingSenderId: '200080333384',
    projectId: 'tripzo-a6939',
    storageBucket: 'tripzo-a6939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwoJfeiSsDxw7GAsd4zB3LHBx-DcuRDqI',
    appId: '1:200080333384:ios:8713a3b679c28b5105967d',
    messagingSenderId: '200080333384',
    projectId: 'tripzo-a6939',
    storageBucket: 'tripzo-a6939.firebasestorage.app',
    iosBundleId: 'com.example.studentride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwoJfeiSsDxw7GAsd4zB3LHBx-DcuRDqI',
    appId: '1:200080333384:ios:8713a3b679c28b5105967d',
    messagingSenderId: '200080333384',
    projectId: 'tripzo-a6939',
    storageBucket: 'tripzo-a6939.firebasestorage.app',
    iosBundleId: 'com.example.studentride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr8Fzd32H8Jqnp2MOrMTZb1IXIRF7-RdI',
    appId: '1:200080333384:web:8ea1b8f5e1011ac105967d',
    messagingSenderId: '200080333384',
    projectId: 'tripzo-a6939',
    authDomain: 'tripzo-a6939.firebaseapp.com',
    storageBucket: 'tripzo-a6939.firebasestorage.app',
    measurementId: 'G-3DN52YMDE5',
  );

}